# =========================
# тЬЕ цпПф╕кчлЩчВ╣щГ╜х┐Ещб╗хоЪхИ╢чЪДхнЧцо╡я╝Их╖▓цФ╣ф╕║хнЯхКацЛЙхЫ╜цЬмхЬ░хМЦя╝Й
# =========================
baseURL = "https://baoliba.pw/"
languageCode = "bn"
languageName = "ржмрж╛ржВрж▓рж╛"
defaultContentLanguage = "bn"
title = "BaoLiba ЁЯЗзЁЯЗй"
theme = "LoveIt"

[params]

  # тЬЕ SEO шо╛ч╜о
  title = "BaoLiba - ржмрж╛ржВрж▓рж╛ржжрзЗрж╢рзЗрж░ ржмрзНрж░рзНржпрж╛ржирзНржб ржПржмржВ ржЗржиржлрзНрж▓рзБржпрж╝рзЗржирзНрж╕рж╛рж░ржжрзЗрж░ ржмрж┐рж╢рзНржмржмрзНржпрж╛ржкрзА рж╕ржВржпрзБржХрзНржд ржХрж░рзЗ"
  description = "BaoLiba ржПржХржЯрж┐ ржХрзНрж░рж╕-ржмрж░рзНржбрж╛рж░ ржЗржиржлрзНрж▓рзБржпрж╝рзЗржирзНрж╕рж╛рж░ ржкрзНрж▓рзНржпрж╛ржЯржлрж░рзНржо ржпрж╛ ржмрж┐рж╢рзНржмрзЗрж░ рзлрзж+ ржжрзЗрж╢рзЗ рж╕рзНржерж╛ржирзАржпрж╝ ржирж┐рж░рзНржорж╛рждрж╛ржжрзЗрж░ рж╕рж╛ржерзЗ ржЧрзНрж▓рзЛржмрж╛рж▓ ржмрзНрж░рзНржпрж╛ржирзНржбржЧрзБрж▓рж┐ржХрзЗ рж╕ржВржпрзБржХрзНржд ржХрж░рзЗред"
  keywords = ["ржЗржиржлрзНрж▓рзБржпрж╝рзЗржирзНрж╕рж╛рж░ ржорж╛рж░рзНржХрзЗржЯрж┐ржВ", "BaoLiba", "ржЧрзНрж▓рзЛржмрж╛рж▓ ржирж┐рж░рзНржорж╛рждрж╛", "ржХрзНрж░рж╕-ржмрж░рзНржбрж╛рж░ ржЗ-ржХржорж╛рж░рзНрж╕"]

  # тЬЕ щб╢щГи Logo
  [params.header.title]
    name = "BaoLiba - ржмрж╛ржВрж▓рж╛ржжрзЗрж╢рзЗрж░ ржмрзНрж░рзНржпрж╛ржирзНржб ржПржмржВ ржЗржиржлрзНрж▓рзБржпрж╝рзЗржирзНрж╕рж╛рж░ржжрзЗрж░ ржмрж┐рж╢рзНржмржмрзНржпрж╛ржкрзА рж╕ржВржпрзБржХрзНржд ржХрж░рзЗ"
    pre = ""
    post = ""
    typeit = false

  # тЬЕ х║ФчФихдЦшзВя╝ИPWAя╝Й
  [params.app]
    title = "BaoLiba ЁЯЗзЁЯЗй"
    svgFavicon = "favicon.png"
    noFavicon = false
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  # тЬЕ ца╖х╝ПцОзхИ╢
  defaultTheme = "light"
  disableThemeSwitch = true
  customCSS = ["css/extended.css"]

  # тЬЕ члЩчВ╣хЫ╛цаЗ
  [params.assets]
    favicon = "/favicon.png"

  # тЬЕ щб╡шДЪхЖЕхо╣
  [params.footer]
    enable = true
    hugo = false
    author = false
    copyright = false
    since = 2025
    custom = '''
    <div class="footer-links">
      <a href="https://baoliba.com/" target="_blank" rel="noopener">BaoLiba</a> |
      <a href="/about/">рж╕ржорзНржкрж░рзНржХрзЗ</a> |
      <a href="/privacy-policy/">ржкрзНрж░рж╛ржЗржнрзЗрж╕рж┐ ржкрж▓рж┐рж╕рж┐</a> |
      <a href="/terms-of-use/">ржмрзНржпржмрж╣рж╛рж░рзЗрж░ рж╢рж░рзНрждрж╛ржмрж▓рзА</a> |
      <a href="/contact-us/">ржпрзЛржЧрж╛ржпрзЛржЧ ржХрж░рзБржи</a>
    </div>
    '''

  # тЬЕ щб╡щЭвшо╛ч╜о
  [params.page]
    author = false
    layout = "post"

# =========================
# тЬЕ щАЪчФищЕНч╜оя╝ИцЙАцЬЙчлЩчВ╣щГ╜хПпхЕ▒чФия╝МцЧащЬАф┐оцФ╣я╝Й
# =========================
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
canonifyURLs = true
uglyURLs = false

[markup.highlight]
  noClasses = false

[frontmatter]
  format = "yaml"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2








